name: Publish a Python distribution to PyPI

on:
  push:
    branches:
      - main

jobs:
  publish_to_pypi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 

      - name: Build and publish package
        run: |-
            python -m pip install --user --upgrade setuptools wheel
            python -m pip install --user --upgrade twine
            python setup.py sdist bdist_wheel
            python -m twine upload  dist/* -u __token__ -p ${{ secrets.PYPI_API_TOKEN }} --non-interactive